export const GET_CAMPAIGN_LOADING = 'GET_CAMPAIGN_LOADING';
export const GET_CAMPAIGN_SUCCESS = 'GET_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN_ERROR = 'GET_CAMPAIGN_ERROR';

export const SORTED_LOADING = 'SORTED_LOADING';
export const SORTED_SUCCESS = 'SORTED_SUCCESS';
